#! /bin/sh
#  bootstrap: Script for regenerating the whole circus.
#  Copyright (C) 2023-2025 streaksu
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -ex

# Keep cd from picking a same-named directory out of CDPATH.
# Assigned first, as some shells fail to unset an unset variable.
CDPATH=
unset CDPATH

# Keep git from being pointed at another repository, as happens in hooks.
# They are assigned first for the same reason as CDPATH.
GIT_DIR= GIT_WORK_TREE= GIT_COMMON_DIR= GIT_INDEX_FILE= GIT_OBJECT_DIRECTORY=
unset GIT_DIR GIT_WORK_TREE GIT_COMMON_DIR GIT_INDEX_FILE GIT_OBJECT_DIRECTORY

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

: "${AUTORECONF:=autoreconf}"
: "${AUTOMAKE:=automake}"

cd "$srcdir"

AUXFILES="config.guess config.sub install-sh"

clone_repo_commit() {
    if test -d "$2/.git"; then
        ( cd "$2" && git reset --hard )
        ( cd "$2" && git clean -f -d )
        if ! ( cd "$2" && git checkout -q $3 ); then
            rm -rf "$2"
        fi
    else
        if test -d "$2"; then
            set +x
            echo "error: '$2' is not a Git repository" 1>&2
            exit 1
        fi
    fi
    if ! test -d "$2"; then
        git clone $1 "$2"
        if ! ( cd "$2" && git checkout -q $3 ); then
            rm -rf "$2"
            exit 1
        fi
    fi
}

if ! test -f version; then
    clone_repo_commit \
        https://github.com/osdev0/freestanding-c-hdrs.git \
        freestanding-c-hdrs \
        38fed4e1e3365733ddbfa03b0a28936243ad31e9

    clone_repo_commit \
        https://github.com/osdev0/cc-runtime.git \
        cc-runtime \
        dae79833b57a01b9fd3e359ee31def69f5ae899b

    # 3.1.2
    clone_repo_commit \
        https://github.com/Mintsuki/Flanterm.git \
        flanterm \
        e231edd0e508022521c8233392aabc8ce5c9b242

    # 6.1.1
    clone_repo_commit \
        https://github.com/uACPI/uACPI.git \
        uacpi \
        fd92d3f3bdd614afda47d08ff5fc373c6d1e4c27
fi

for auxfile in $AUXFILES; do
    rm -f build-aux/$auxfile
done

$AUTORECONF -fvi -Wall

# Take the auxiliary files from automake, whose copies tend to be more up to
# date than the ones autoreconf installs.
AUTOMAKE_LIBDIR="$($AUTOMAKE --print-libdir 2>/dev/null)" || true
if test -z "$AUTOMAKE_LIBDIR"; then
    set +x
    echo "error: Missing or broken automake." 1>&2
    echo "       Please make sure automake is installed and working." 1>&2
    exit 1
fi
mkdir -p build-aux
for auxfile in $AUXFILES; do
    cp "$AUTOMAKE_LIBDIR/$auxfile" build-aux/
    chmod +x build-aux/$auxfile
done

set +x

printf "\nSource tree bootstrapped successfully!\n"
