name: Ironclad CI

on: [push, pull_request]

jobs:
  ci_build:
    name: Check for compilation failures
    runs-on: codeberg-small
    container: debian:sid
    strategy:
      matrix:
        target_arch: [riscv64-limine, x86_64-limine]

    steps:
      - name: Create resolv.conf
        run: |
          set -ex
          echo 'nameserver 8.8.8.8' >/etc/resolv.conf
          echo 'nameserver 8.8.4.4' >>/etc/resolv.conf

      - name: Install dependencies
        run: apt-get update && apt-get -y dist-upgrade && apt-get install -y nodejs wget autoconf automake git build-essential findutils make texinfo highlight gprbuild

      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v5

      - name: Install architecture-specific dependencies
        run: |
          set -ex

          case "${{matrix.target_arch}}" in \
            riscv64-limine) \
              TOOLCHAIN_PREFIX="riscv64-linux-gnu-"; \
              apt-get install -y gcc-15-riscv64-linux-gnu gnat-15-riscv64-linux-gnu ;; \
            x86_64-limine) \
              TOOLCHAIN_PREFIX=""; \
              apt-get install -y gcc-15 gnat-15 ;; \
          esac

          mkdir toolchain_dir
          for i in gcc gcc-ar gcc-nm gcc-ranlib gcov gcov-dump gcov-tool lto-dump gnat gnatbind gnatchop gnatclean gnathtml gnatkr gnatlink gnatls gnatmake gnatname gnatprep; do
            ln -s /usr/bin/$TOOLCHAIN_PREFIX$i-15 toolchain_dir/$TOOLCHAIN_PREFIX$i
          done

      - name: Fetch gnatprove
        run: |
          set -ex
          wget https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-15.1.0-1/gnatprove-x86_64-linux-15.1.0-1.tar.gz
          tar -xf gnatprove-x86_64-linux-15.1.0-1.tar.gz
          rm gnatprove-x86_64-linux-15.1.0-1.tar.gz

      - name: Bootstrap
        run: ./bootstrap

      - name: Build
        run: |
          set -ex

          export PATH="$PWD/gnatprove-x86_64-linux-15.1.0-1/bin:$PWD/toolchain_dir:$PATH"

          case "${{matrix.target_arch}}" in \
            riscv64-limine) \
              ./configure --host=riscv64-linux-gnu ;; \
            x86_64-limine) \
              ./configure ;; \
          esac

          make
          make check-rts-stone
          make check-kernel-stone
