name: CI

on: [push, pull_request]

jobs:
  build_and_check:
    name: Build project and check
    runs-on: docker
    container: debian:sid
    strategy:
      matrix:
        target_arch: [riscv64-limine, x86_64-limine]

    steps:
      - name: Create resolv.conf
        run: |
          set -ex
          echo 'nameserver 8.8.8.8' >/etc/resolv.conf
          echo 'nameserver 8.8.4.4' >>/etc/resolv.conf

      - name: Sync and install basic dependencies
        run: apt-get update && apt-get -y dist-upgrade && apt-get install -y nodejs wget git

      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v5

      - name: Install project dependencies
        run: |
          set -ex

          apt-get install -y autoconf automake build-essential findutils make texinfo highlight gprbuild

          case "${{matrix.target_arch}}" in \
            riscv64-limine) \
              TOOLCHAIN_PREFIX="riscv64-linux-gnu-"; \
              apt-get install -y gcc-15-riscv64-linux-gnu gnat-15-riscv64-linux-gnu ;; \
            x86_64-limine) \
              TOOLCHAIN_PREFIX=""; \
              apt-get install -y gcc-15 gnat-15 ;; \
          esac

          mkdir toolchain_dir
          for i in gcc gcc-ar gcc-nm gcc-ranlib gcov gcov-dump gcov-tool lto-dump gnat gnatbind gnatchop gnatclean gnathtml gnatkr gnatlink gnatls gnatmake gnatname gnatprep; do
            ln -s /usr/bin/$TOOLCHAIN_PREFIX$i-15 toolchain_dir/$TOOLCHAIN_PREFIX$i
          done

          wget https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-15.1.0-1/gnatprove-x86_64-linux-15.1.0-1.tar.gz
          tar -xf gnatprove-x86_64-linux-15.1.0-1.tar.gz
          mv gnatprove-x86_64-linux-15.1.0-1.tar.gz gnatprove-tool

          wget https://github.com/crate-ci/typos/releases/download/v1.45.0/typos-v1.45.0-x86_64-unknown-linux-musl.tar.gz
          mkdir typos-tool
          tar xf typos-v1.45.0-x86_64-unknown-linux-musl.tar.gz -C typos-tool

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure step
        run: |
          set -ex
          export PATH="$PWD/toolchain_dir:$PWD/gnatprove-tool/bin:$PWD/typos-tool/bin:$PATH"
          case "${{matrix.target_arch}}" in \
            riscv64-limine) \
              GNATPROVE=gnatprove TYPOS=typos ./configure --host=riscv64-linux-gnu ;; \
            x86_64-limine) \
              GNATPROVE=gnatprove TYPOS=typos ./configure ;; \
          esac

      - name: Build
        run: |
          set -ex
          export PATH="$PWD/toolchain_dir:$PWD/gnatprove-tool/bin:$PWD/typos-tool/bin:$PATH"
          make -j$(nproc)

      - name: Check typos
        run: |
          set -ex
          export PATH="$PWD/toolchain_dir:$PWD/gnatprove-tool/bin:$PWD/typos-tool/bin:$PATH"
          make check-typos -j$(nproc)

      - name: Verify RTS
        run: |
          set -ex
          export PATH="$PWD/toolchain_dir:$PWD/gnatprove-tool/bin:$PWD/typos-tool/bin:$PATH"
          make check-rts-stone -j$(nproc)

      - name: Verify kernel
        run: |
          set -ex
          export PATH="$PWD/toolchain_dir:$PWD/gnatprove-tool/bin:$PWD/typos-tool/bin:$PATH"
          make check-kernel-stone -j$(nproc)
