name: CI

on:
  push:
    paths:
      - 'source/**'
      - 'bootstrap'
      - 'configure.ac'
      - 'GNUmakefile.in'
      - 'ironclad.gpr.in'
      - 'rts.gpr.in'
      - 'version.sh'
  pull_request:
    paths:
      - 'source/**'
      - 'bootstrap'
      - 'configure.ac'
      - 'GNUmakefile.in'
      - 'ironclad.gpr.in'
      - 'rts.gpr.in'
      - 'version.sh'

jobs:
  build_and_check:
    name: Build project and check
    runs-on: docker
    container: debian:sid
    strategy:
      matrix:
        target_arch: [riscv64-limine, x86_64-limine]

    steps:
      - name: Sync and install basic dependencies
        run: apt-get update && apt-get -y dist-upgrade && apt-get install -y nodejs wget git autoconf automake build-essential findutils make texinfo highlight

      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Install project dependencies
        run: |
          set -ex

          wget https://github.com/alire-project/GNAT-FSF-builds/releases/download/gprbuild-26.0.0-1/gprbuild-x86_64-linux-26.0.0-1.tar.gz
          echo 'bd15fadcb457e9f8abbf1489d867878bc5a4ee4c6c923f72ab12986cd02f9b379045eeb4bfa05b119c2da2ff303f79ec519f567fc5b0c0f761fefc52085f0782  gprbuild-x86_64-linux-26.0.0-1.tar.gz' | sha512sum -c
          tar -xf gprbuild-x86_64-linux-26.0.0-1.tar.gz
          mv gprbuild-x86_64-linux-26.0.0-1 gprbuild-tool

          case "${{matrix.target_arch}}" in \
            riscv64-limine) \
              wget https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.1.0-1/gnat-riscv64-elf-linux64-x86_64-16.1.0-1.tar.gz ; \
              echo 'ccf2c930eb29d369e027e328d7ba0dd97f4ddd610564a59af3663c691e16292511c4e947af8c9c028a864d7573694f46eb96e42cbfb12820abccda9edc86df0d  gnat-riscv64-elf-linux64-x86_64-16.1.0-1.tar.gz' | sha512sum -c ; \
              tar -xf gnat-riscv64-elf-linux64-x86_64-16.1.0-1.tar.gz ; \
              mv gnat-riscv64-elf-linux64-x86_64-16.1.0-1 gnat-tool ;; \
            x86_64-limine) \
              wget https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.1.0-1/gnat-x86_64-linux-16.1.0-1.tar.gz ; \
              echo '234ce37d0e9608ed69e66bfb4f7a91134446f25a775550eddc36fd411bbaedf39a3a0c85f25c5e935e95435ed5827525e427ba26cc4b16e6ec99262b14f086bf  gnat-x86_64-linux-16.1.0-1.tar.gz' | sha512sum -c ; \
              tar -xf gnat-x86_64-linux-16.1.0-1.tar.gz ; \
              mv gnat-x86_64-linux-16.1.0-1 gnat-tool ;; \
          esac

          wget https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-16.1.0-1/gnatprove-x86_64-linux-16.1.0-1.tar.gz
          echo 'f3dda147455da5c9dbdc6ab320432e7d6e643eb3c1a1d9614694a585360cca636eef5522e94e234b7c0ef98e70c4b7747d5ad94345176204ef28e5463148779c  gnatprove-x86_64-linux-16.1.0-1.tar.gz' | sha512sum -c
          tar -xf gnatprove-x86_64-linux-16.1.0-1.tar.gz
          mv gnatprove-x86_64-linux-16.1.0-1 gnatprove-tool

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure step
        run: |
          set -ex
          export PATH="$PWD/gprbuild-tool/bin:$PWD/gnat-tool/bin:$PWD/gnatprove-tool/bin:$PATH"
          case "${{matrix.target_arch}}" in \
            riscv64-limine) \
              ./configure --host=riscv64-elf ;; \
            x86_64-limine) \
              ./configure ;; \
          esac

      - name: Build
        run: |
          set -ex
          export PATH="$PWD/gprbuild-tool/bin:$PWD/gnat-tool/bin:$PWD/gnatprove-tool/bin:$PATH"
          make -j$(nproc)

      - name: Verify RTS
        run: |
          set -ex
          export PATH="$PWD/gprbuild-tool/bin:$PWD/gnat-tool/bin:$PWD/gnatprove-tool/bin:$PATH"
          make check-rts -j$(nproc)

      - name: Verify kernel (stone level)
        run: |
          set -ex
          export PATH="$PWD/gprbuild-tool/bin:$PWD/gnat-tool/bin:$PWD/gnatprove-tool/bin:$PATH"
          make check-kernel-stone -j$(nproc)
