name: Ironclad CI

on: [push, pull_request]

jobs:
  ci_build:
    name: Check for compilation failures
    runs-on: codeberg-small
    container: debian:sid
    strategy:
      matrix:
        target_arch: [riscv64-limine, x86_64-limine]

    steps:
      - name: Create resolv.conf
        run: |
          set -ex
          echo 'nameserver 8.8.8.8' >/etc/resolv.conf
          echo 'nameserver 8.8.4.4' >>/etc/resolv.conf

      - name: Install dependencies
        run: apt-get update && apt-get -y dist-upgrade && apt-get install -y nodejs wget autoconf automake git build-essential findutils make texinfo highlight gprbuild gnat

      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Fetch gnatprove
        run: |
          set -ex
          wget https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-15.1.0-1/gnatprove-x86_64-linux-15.1.0-1.tar.gz
          tar -xf gnatprove-x86_64-linux-15.1.0-1.tar.gz
          rm gnatprove-x86_64-linux-15.1.0-1.tar.gz

      - name: Bootstrap
        run: ./bootstrap

      - name: Build
        run: |
          set -ex

          export PATH=$PWD/gnatprove-x86_64-linux-15.1.0-1/bin:$PATH

          case "${{matrix.target_arch}}" in \
            riscv64-limine) \
              wget https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-14.2.0-1/gnat-riscv64-elf-linux64-x86_64-14.2.0-1.tar.gz; \
              tar -xf gnat-riscv64-elf-linux64-x86_64-14.2.0-1.tar.gz; \
              rm gnat-riscv64-elf-linux64-x86_64-14.2.0-1.tar.gz; \
              export PATH=$PWD/gnat-riscv64-elf-linux64-x86_64-14.2.0-1/bin:$PATH; \
              ln -s riscv64-elf-gnatbind gnat-riscv64-elf-linux64-x86_64-14.2.0-1/bin/riscv64-elf-gnatbind-14; \
              ./configure --host=riscv64-elf ;; \
            x86_64-limine) \
              ./configure ;; \
          esac

          make
          make check-rts-stone
          make check-kernel-stone
